---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

# https://github.com/jgsqware/clairctl
    - name: "deploy clairctl on bionic amd64"
      dist: bionic
      arch: amd64
      sudo: false
      language: python
      # python: 3.7
      services:
        - docker 
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        # Master branch version
        - curl -L https://raw.githubusercontent.com/jgsqware/clairctl/master/install.sh | sudo sh
      after_success:
        - deactivate
